### ISSUE TITLE
Problem with generating BAM file

### ISSUE THREAD

**Issue by Chris-lang478** [cellgeni/STARsolo#1]
Hi,apredeus
I got a problem while generating BAM files using starsolo_strt.sh. I am trying to map multiple files. However, I am seeing only one single set of output files rather than one for each sample. 
And readFilesIn  xx2301_1.fastq.gz,xx2306_1.fastq.gz   xx2301_2.fastq.gz,xx2306_2.fastq.gz.
However, I got only one Bam file and output.

**Comment by apredeus** [comment]
Hi Chris,

This is expected behaviour - the goal was to combine multiple sequencing outputs (e.g. sequencing lanes) that originated from the same single cell library - i.e. with same set of cells defined by unique barcodes. The BAM file will have the (corrected) barcode and UMI sequence for each cell, thus, they can be separated later if necessary. 

If you have a different reasoning and want separate BAM files, just run the script twice - in your example, using sample identifier (`$TAG`) xx2301 and xx2306, respectively. 

Cheers
-- Alex
