### ISSUE TITLE
STARsolo for 10X Chromium fastqs with HTO libraries

### ISSUE THREAD

**Issue by OluwayioseOA** [cellgeni/STARsolo#10]
Hi Alex,
I have some 10X chromium fastq libraries (R1/R2), each with HTO libraries (R1/R2) for sample demultiplexing. I successfully ran "cellranger count" but we wanted to replicate this using STARsolo. However, I did not find the option to include the HTO libraries in my line of code (please see below). Please would you have any suggestion for me on this?

STAR --runThreadN 2 --runDirPerm All_RWX --runRNGseed 1 --genomeDir /index --readFilesIn /data/S1_L001_R2_001.fastq.gz /data/S1_L001_R1_001.fastq.gz --readFilesCommand zcat --limitBAMsortRAM 120000000000 --outMultimapperOrder Random --outSAMtype BAM SortedByCoordinate --outSAMattributes NH HI AS nM CB UB GX GN --outBAMsortingThreadN 2 --outFilterScoreMin 30 --clipAdapterType CellRanger4 --soloType CB_UMI_Simple --soloUMIstart 17 --soloCBlen 16 --soloUMIlen 12 --soloBarcodeReadLength 0 --soloCBwhitelist /data/starsolo/3M-february-2018.txt --soloStrand Forward   --soloOutFileNames S1/ features.tsv barcodes.tsv matrix.mtx --soloFeatures Gene GeneFull Velocyto --soloUMIdedup 1MM_CR --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloCellFilter EmptyDrops_CR --soloUMIfiltering MultiGeneUMI_CR --outTmpDir STARtmp_S1 --outFileNamePrefix S1/S1

**Comment by apredeus** [comment]
Hi, 

Sorry, totally forgot to answer you! There is no option to process HTO or ADT datasets in STARsolo, unfortunately. However you always can process the gene expression part (GEX) of your experiment separately (since HTO usually is done together with GEX). That would be normal STARsolo, run as usual. After this you can take the results of demultiplexing (i.e. barcode to sample table) and use it on your STARsolo results.
