### ISSUE TITLE
STARsolo for Visium Data Alignment

### ISSUE THREAD

**Issue by OluwayioseOA** [cellgeni/STARsolo#9]
Hi Alex,

Please I wanted verify if you guys are planning to upgrade STARsolo for Visium (Spatial) data alignment as an alternative to spaceranger.

Thanks
Oladele

**Comment by apredeus** [comment]
Hello Oladele, 

I think STARsolo could be used as is with the Visium data - all you need to do is provide it with appropriate whitelist. However, I would not do it, because there are several image-related things that Space Ranger does, which would be hard to implement in STARsolo. For example, it can rotate the image to match the expression, and so on. This is just my opinion, as I did not dig into the upstream processing of Visium much. 

Hope this helps!

-- Alex

**Comment by OluwayioseOA** [comment]
Hi Alex,

Thanks for a prompt response. That was exactly my observation after
applying STARsolo to Visium but there was no option to process the image
(.tiff) files (as in Spaceranger).

On another note, is whitelist also recommended for Chromium data alignment
or not?


Best,
*OLUWAYIOSE, Oladele Amos PhD.*

**Comment by apredeus** [comment]
Hi Oladele, 

Yes for 10x Chromium whitelist is a must - it increases the sensitivity of barcode detection noticeably. Our scripts would not work if there is no appropriate whitelist (== Chromium chemistry version) identified.

**Comment by OluwayioseOA** [comment]
Thanks Apredeus for prompt responses. I have another question related to STARsolo for Chromium but will open a separate issue for it. Thanks once again!
